#!/bin/bash

python3 scripts/benchmarking/e2e/run_systests.py \
  --queries \
  inference/solar_power/threading/nbeats-24.test:01 \
  inference/solar_power/threading/nbeats-24.test:02 \
  inference/solar_power/threading/nbeats-24.test:03 \
  inference/solar_power/threading/nbeats-24.test:04 \
  inference/solar_power/threading/nbeats-24.test:05 \
  inference/solar_power/threading/nbeats-24.test:06 \
  inference/solar_power/threading/nbeats-24.test:07 \
  inference/solar_power/threading/nbeats-24.test:08 \
  inference/solar_power/threading/dlinear-24.test:01 \
  inference/solar_power/threading/dlinear-24.test:02 \
  inference/solar_power/threading/dlinear-24.test:03 \
  inference/solar_power/threading/dlinear-24.test:04 \
  inference/solar_power/threading/dlinear-24.test:05 \
  inference/solar_power/threading/dlinear-24.test:06 \
  inference/solar_power/threading/dlinear-24.test:07 \
  inference/solar_power/threading/dlinear-24.test:08 \
  inference/solar_power/threading/nbeats-48.test:01 \
  inference/solar_power/threading/nbeats-48.test:02 \
  inference/solar_power/threading/nbeats-48.test:03 \
  inference/solar_power/threading/nbeats-48.test:04 \
  inference/solar_power/threading/nbeats-48.test:05 \
  inference/solar_power/threading/nbeats-48.test:06 \
  inference/solar_power/threading/nbeats-48.test:07 \
  inference/solar_power/threading/nbeats-48.test:08 \
  inference/solar_power/threading/nbeats-48.test:09 \
  inference/solar_power/threading/nbeats-48.test:10 \
  inference/solar_power/threading/dlinear-48.test:01 \
  inference/solar_power/threading/dlinear-48.test:02 \
  inference/solar_power/threading/dlinear-48.test:03 \
  inference/solar_power/threading/dlinear-48.test:04 \
  inference/solar_power/threading/dlinear-48.test:05 \
  inference/solar_power/threading/dlinear-48.test:06 \
  inference/solar_power/threading/dlinear-48.test:07 \
  inference/solar_power/threading/dlinear-48.test:08 \
  inference/solar_power/threading/dlinear-48.test:09 \
  inference/solar_power/threading/dlinear-48.test:10 \
  inference/solar_power/threading/nbeats-96.test:01 \
  inference/solar_power/threading/nbeats-96.test:02 \
  inference/solar_power/threading/nbeats-96.test:03 \
  inference/solar_power/threading/nbeats-96.test:04 \
  inference/solar_power/threading/nbeats-96.test:05 \
  inference/solar_power/threading/nbeats-96.test:06 \
  inference/solar_power/threading/nbeats-96.test:07 \
  inference/solar_power/threading/nbeats-96.test:08 \
  inference/solar_power/threading/nbeats-96.test:09 \
  inference/solar_power/threading/nbeats-96.test:10 \
  inference/solar_power/threading/dlinear-96.test:01 \
  inference/solar_power/threading/dlinear-96.test:02 \
  inference/solar_power/threading/dlinear-96.test:03 \
  inference/solar_power/threading/dlinear-96.test:04 \
  inference/solar_power/threading/dlinear-96.test:05 \
  inference/solar_power/threading/dlinear-96.test:06 \
  inference/solar_power/threading/dlinear-96.test:07 \
  inference/solar_power/threading/dlinear-96.test:08 \
  inference/solar_power/threading/dlinear-96.test:09 \
  inference/solar_power/threading/dlinear-96.test:10 \
  inference/solar_power/threading/nanodet-24.test:01 \
  inference/solar_power/threading/nanodet-24.test:02 \
  inference/solar_power/threading/nanodet-24.test:03 \
  inference/solar_power/threading/nanodet-24.test:04 \
  inference/solar_power/threading/nanodet-24.test:05 \
  inference/solar_power/threading/nanodet-24.test:06 \
  inference/solar_power/threading/nanodet-24.test:07 \
  inference/solar_power/threading/nanodet-24.test:08 \
  inference/solar_power/threading/mlp-24.test:01 \
  inference/solar_power/threading/mlp-24.test:02 \
  inference/solar_power/threading/mlp-24.test:03 \
  inference/solar_power/threading/mlp-24.test:04 \
  inference/solar_power/threading/mlp-24.test:05 \
  inference/solar_power/threading/mlp-24.test:06 \
  inference/solar_power/threading/mlp-24.test:07 \
  inference/solar_power/threading/mlp-24.test:08 \
  inference/solar_power/threading/nanodet-48.test:01 \
  inference/solar_power/threading/nanodet-48.test:02 \
  inference/solar_power/threading/nanodet-48.test:03 \
  inference/solar_power/threading/nanodet-48.test:04 \
  inference/solar_power/threading/nanodet-48.test:05 \
  inference/solar_power/threading/nanodet-48.test:06 \
  inference/solar_power/threading/nanodet-48.test:07 \
  inference/solar_power/threading/nanodet-48.test:08 \
  inference/solar_power/threading/nanodet-48.test:09 \
  inference/solar_power/threading/nanodet-48.test:10 \
  inference/solar_power/threading/mlp-48.test:01 \
  inference/solar_power/threading/mlp-48.test:02 \
  inference/solar_power/threading/mlp-48.test:03 \
  inference/solar_power/threading/mlp-48.test:04 \
  inference/solar_power/threading/mlp-48.test:05 \
  inference/solar_power/threading/mlp-48.test:06 \
  inference/solar_power/threading/mlp-48.test:07 \
  inference/solar_power/threading/mlp-48.test:08 \
  inference/solar_power/threading/mlp-48.test:09 \
  inference/solar_power/threading/mlp-48.test:10 \
  inference/solar_power/threading/nanodet-96.test:01 \
  inference/solar_power/threading/nanodet-96.test:02 \
  inference/solar_power/threading/nanodet-96.test:03 \
  inference/solar_power/threading/nanodet-96.test:04 \
  inference/solar_power/threading/nanodet-96.test:05 \
  inference/solar_power/threading/nanodet-96.test:06 \
  inference/solar_power/threading/nanodet-96.test:07 \
  inference/solar_power/threading/nanodet-96.test:08 \
  inference/solar_power/threading/nanodet-96.test:09 \
  inference/solar_power/threading/nanodet-96.test:10 \
  inference/solar_power/threading/mlp-96.test:01 \
  inference/solar_power/threading/mlp-96.test:02 \
  inference/solar_power/threading/mlp-96.test:03 \
  inference/solar_power/threading/mlp-96.test:04 \
  inference/solar_power/threading/mlp-96.test:05 \
  inference/solar_power/threading/mlp-96.test:06 \
  inference/solar_power/threading/mlp-96.test:07 \
  inference/solar_power/threading/mlp-96.test:08 \
  inference/solar_power/threading/mlp-96.test:09 \
  inference/solar_power/threading/mlp-96.test:10 \
  --inference-config scripts/benchmarking/e2e/config/inference_default.yaml \
  --repetitions 10
