"optimizer.inference_batch_size": [1]
"worker.default_query_execution.inference.use_batch_deduplication": [false]
"worker.default_query_execution.inference.prediction_cache_type": ["SECOND_CHANCE"]
"worker.default_query_execution.inference.number_of_entries_prediction_cache": [256]
"worker.default_query_execution.inference.openvino_inference_num_threads": [1]
"worker.default_query_execution.inference.openvino_num_streams": [0]
"worker.default_query_execution.inference.openvino_enable_cpu_pinning": [false]